Pandas for Data Wrangling: DataFramea, Cleaning, GroupBy & Merging

Assignments :

1.Full Pipeline: Clean the Orders Dataset

In [1]:
import pandas as pd
import numpy as np
#load data
df = pd.read_csv("data.csv")
df

   order_id        customer        city  amount     status
0      5001     Rahul Verma      Mumbai    2500  Delivered
1      5002  Fatima Sheikh       mumbai    1800  Delivered
2      5003     Suresh Iyer   Bangalore          Delivered
3      5004     Meena Joshi   BANGALORE    3200  Cancelled
4      5001     Rahul Verma      Mumbai    2500  Delivered
5      5006     Aakash Bose        Pune    4100  Delivered
6      5007      Divya Nair     Chennai            Pending

In [2]:
#Convert fake null value to naN
df = df.replace(r'^\s*$', np.nan,regex=True)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   order_id   7 non-null      int64
 1    customer  7 non-null      str
 2    city      7 non-null      str
 3    amount    5 non-null      str
 4    status    7 non-null      str
dtypes: int64(1), str(4)
memory usage: 412.0 bytes

In [4]:
print(df.columns.tolist())

['order_id', ' customer', ' city', ' amount', ' status']

In [5]:
#*Remove Extra space from column*(Main reason this entire data):

df.columns = df.columns.str.strip()

print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['order_id', 'customer', 'city', 'amount', 'status'], dtype='str')>

In [6]:
#Clean text columns:

text_column = ['customer','city','status']
for col in text_column:
    df[col] = df[col].str.strip()

In [7]:
#Standardize city name:

df['city'] = df['city'].str.title()

In [8]:
df

   order_id       customer       city amount     status
0      5001    Rahul Verma     Mumbai   2500  Delivered
1      5002  Fatima Sheikh     Mumbai   1800  Delivered
2      5003    Suresh Iyer  Bangalore    NaN  Delivered
3      5004    Meena Joshi  Bangalore   3200  Cancelled
4      5001    Rahul Verma     Mumbai   2500  Delivered
5      5006    Aakash Bose       Pune   4100  Delivered
6      5007     Divya Nair    Chennai    NaN    Pending

In [9]:
#Convert amount to numeric:

df.dtypes

order_id    int64
customer      str
city          str
amount        str
status        str
dtype: object

In [10]:
df['amount'] = pd.to_numeric(df['amount'],errors='coerce')

In [11]:
df.dtypes

order_id      int64
customer        str
city            str
amount      float64
status          str
dtype: object

In [12]:
df

   order_id       customer       city  amount     status
0      5001    Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh     Mumbai  1800.0  Delivered
2      5003    Suresh Iyer  Bangalore     NaN  Delivered
3      5004    Meena Joshi  Bangalore  3200.0  Cancelled
4      5001    Rahul Verma     Mumbai  2500.0  Delivered
5      5006    Aakash Bose       Pune  4100.0  Delivered
6      5007     Divya Nair    Chennai     NaN    Pending

In [13]:
#Chck missing value and duplicate:
print("Missing value: ",df.isnull().sum())
print("Duplicate Value: ",df.duplicated().sum())

Missing value:  order_id    0
customer    0
city        0
amount      2
status      0
dtype: int64
Duplicate Value:  1

In [14]:
#Remove Dublicate rows:
df = df.drop_duplicates()

print("After Remove duplicate: ", df.shape)

After Remove duplicate:  (6, 5)

In [15]:
df

   order_id       customer       city  amount     status
0      5001    Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh     Mumbai  1800.0  Delivered
2      5003    Suresh Iyer  Bangalore     NaN  Delivered
3      5004    Meena Joshi  Bangalore  3200.0  Cancelled
5      5006    Aakash Bose       Pune  4100.0  Delivered
6      5007     Divya Nair    Chennai     NaN    Pending

In [16]:
#Fill Missing amount using City:

df['amount'] = df.groupby('city')['amount'].transform(lambda x: x.fillna(x.mean()))
df

   order_id       customer       city  amount     status
0      5001    Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh     Mumbai  1800.0  Delivered
2      5003    Suresh Iyer  Bangalore  3200.0  Delivered
3      5004    Meena Joshi  Bangalore  3200.0  Cancelled
5      5006    Aakash Bose       Pune  4100.0  Delivered
6      5007     Divya Nair    Chennai     NaN    Pending

In [17]:
#Verify Missing Value:
print("Missing amount after cleaning: ", df['amount'].isnull().sum())

Missing amount after cleaning:  1

2.Multi-Column GroupBy

In [18]:
df2 = pd.read_csv("assignment_2_student_dataset.csv")
df2

    student_id           name        department  marks  semester
0          101  Ananya Sharma  Computer Science     88         4
1          102   Vikram Singh  Computer Science     72         4
2          103    Priya Patel  Computer Science     91         4
3          104    Karan Mehta        Mechanical     58         3
4          105    Rahul Verma        Mechanical     64         3
5          106      Sneha Das        Mechanical     52         3
6          107     Amit Kumar       Electronics     75         4
7          108     Neha Joshi       Electronics     69         4
8          109     Rohan Nair       Electronics     72         4
9          110     Pooja Iyer  Computer Science     81         3
10         111      Arjun Rao        Mechanical     61         4
11         112    Meena Singh       Electronics     70         3

In [19]:
#The assignment specify ask for:

df2.groupby(['department','semester'])

In [20]:
result = (
    df2.groupby(["department", "semester"])["marks"]
      .mean()
)

result

department        semester
Computer Science  3           81.000000
                  4           83.666667
Electronics       3           70.000000
                  4           72.000000
Mechanical        3           58.000000
                  4           61.000000
Name: marks, dtype: float64

3.Assignment 3 — Inner vs Left Merge

In [21]:
#take ass 2 reference dataset in department column take :
depart_col = pd.DataFrame(df2['department'])

In [22]:
depart_col

          department
0   Computer Science
1   Computer Science
2   Computer Science
3         Mechanical
4         Mechanical
5         Mechanical
6        Electronics
7        Electronics
8        Electronics
9   Computer Science
10        Mechanical
11       Electronics

In [23]:
#Remove duplicate :
depart_col = depart_col.drop_duplicates()

depart_col

         department
0  Computer Science
3        Mechanical
6       Electronics

In [24]:
#Left Merge:
left_merge = pd.merge(
    df2,
    depart_col,
    on="department",
    how="left"
)

print(left_merge)
print("Rows:", len(left_merge))

    student_id           name        department  marks  semester
0          101  Ananya Sharma  Computer Science     88         4
1          102   Vikram Singh  Computer Science     72         4
2          103    Priya Patel  Computer Science     91         4
3          104    Karan Mehta        Mechanical     58         3
4          105    Rahul Verma        Mechanical     64         3
5          106      Sneha Das        Mechanical     52         3
6          107     Amit Kumar       Electronics     75         4
7          108     Neha Joshi       Electronics     69         4
8          109     Rohan Nair       Electronics     72         4
9          110     Pooja Iyer  Computer Science     81         3
10         111      Arjun Rao        Mechanical     61         4
11         112    Meena Singh       Electronics     70         3
Rows: 12

In [25]:
#Inner Merge:
inner_merge = pd.merge(
    df2,
    df2['department'],
    on="department",
    how="inner"
)

print(inner_merge)
print("Rows:", len(left_merge))

    student_id           name        department  marks  semester
0          101  Ananya Sharma  Computer Science     88         4
1          101  Ananya Sharma  Computer Science     88         4
2          101  Ananya Sharma  Computer Science     88         4
3          101  Ananya Sharma  Computer Science     88         4
4          102   Vikram Singh  Computer Science     72         4
5          102   Vikram Singh  Computer Science     72         4
6          102   Vikram Singh  Computer Science     72         4
7          102   Vikram Singh  Computer Science     72         4
8          103    Priya Patel  Computer Science     91         4
9          103    Priya Patel  Computer Science     91         4
10         103    Priya Patel  Computer Science     91         4
11         103    Priya Patel  Computer Science     91         4
12         104    Karan Mehta        Mechanical     58         3
13         104    Karan Mehta        Mechanical     58         3
14         104    Karan Mehta        Mechanical     58         3
15         104    Karan Mehta        Mechanical     58         3
16         105    Rahul Verma        Mechanical     64         3
17         105    Rahul Verma        Mechanical     64         3
18         105    Rahul Verma        Mechanical     64         3
19         105    Rahul Verma        Mechanical     64         3
20         106      Sneha Das        Mechanical     52         3
21         106      Sneha Das        Mechanical     52         3
22         106      Sneha Das        Mechanical     52         3
23         106      Sneha Das        Mechanical     52         3
24         107     Amit Kumar       Electronics     75         4
25         107     Amit Kumar       Electronics     75         4
26         107     Amit Kumar       Electronics     75         4
27         107     Amit Kumar       Electronics     75         4
28         108     Neha Joshi       Electronics     69         4
29         108     Neha Joshi       Electronics     69         4
30         108     Neha Joshi       Electronics     69         4
31         108     Neha Joshi       Electronics     69         4
32         109     Rohan Nair       Electronics     72         4
33         109     Rohan Nair       Electronics     72         4
34         109     Rohan Nair       Electronics     72         4
35         109     Rohan Nair       Electronics     72         4
36         110     Pooja Iyer  Computer Science     81         3
37         110     Pooja Iyer  Computer Science     81         3
38         110     Pooja Iyer  Computer Science     81         3
39         110     Pooja Iyer  Computer Science     81         3
40         111      Arjun Rao        Mechanical     61         4
41         111      Arjun Rao        Mechanical     61         4
42         111      Arjun Rao        Mechanical     61         4
43         111      Arjun Rao        Mechanical     61         4
44         112    Meena Singh       Electronics     70         3
45         112    Meena Singh       Electronics     70         3
46         112    Meena Singh       Electronics     70         3
47         112    Meena Singh       Electronics     70         3
Rows: 12

Assignment 4 — Filtering with .isin()

In [26]:
#Calculate department avg: 
dept_avg = df2.groupby("department")["marks"].mean()

print(dept_avg)

department
Computer Science    83.00
Electronics         71.50
Mechanical          58.75
Name: marks, dtype: float64

In [27]:
#Filtering depart:
filtered = df2[
    df2["department"].isin(["Computer Science", "Mechanical"])
]

filtered

    student_id           name        department  marks  semester
0          101  Ananya Sharma  Computer Science     88         4
1          102   Vikram Singh  Computer Science     72         4
2          103    Priya Patel  Computer Science     91         4
3          104    Karan Mehta        Mechanical     58         3
4          105    Rahul Verma        Mechanical     64         3
5          106      Sneha Das        Mechanical     52         3
9          110     Pooja Iyer  Computer Science     81         3
10         111      Arjun Rao        Mechanical     61         4

In [28]:
#Comper with dipartment avg, also create department_avg col:
df2["department_avg"] = df2["department"].map(dept_avg)

In [29]:
df2

,student_id,name,department,marks,semester,department_avg
0,101,Ananya Sharma,Computer Science,88,4,83.00
1,102,Vikram Singh,Computer Science,72,4,83.00
2,103,Priya Patel,Computer Science,91,4,83.00
3,104,Karan Mehta,Mechanical,58,3,58.75
4,105,Rahul Verma,Mechanical,64,3,58.75
5,106,Sneha Das,Mechanical,52,3,58.75
6,107,Amit Kumar,Electronics,75,4,71.50
7,108,Neha Joshi,Electronics,69,4,71.50
8,109,Rohan Nair,Electronics,72,4,71.50
9,110,Pooja Iyer,Computer Science,81,3,83.00
10,111,Arjun Rao,Mechanical,61,4,58.75
11,112,Meena Singh,Electronics,70,3,71.50

In [30]:
result = df2[
    df2["department"].isin(["Computer Science", "Mechanical"])
    & (df2["marks"] < df2["department_avg"])
]

print(result[["name", "department", "marks", "department_avg"]])

           name        department  marks  department_avg
1  Vikram Singh  Computer Science     72           83.00
3   Karan Mehta        Mechanical     58           58.75
5     Sneha Das        Mechanical     52           58.75
9    Pooja Iyer  Computer Science     81           83.00